name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i --no-audit --no-fund --no-optional
      - name: Run lint
        run: npm run eslint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
      